import Foundation


struct MockLifeWords {
    static let data: [(String, String)] = [
        // 1. Home & Household (집과 가정)
        ("residence", "주거지"),
        ("dwelling", "주거"),
        ("household", "가정"),
        ("furniture", "가구"),
        ("appliance", "가전제품"),
        ("utensil", "주방 도구"),
        ("cutlery", "수저류"),
        ("crockery", "식기류"),
        ("maintenance", "유지보수"),
        ("repair", "수리"),
        ("renovation", "수리, 개조"),
        ("decoration", "장식"),
        ("utilities", "공과금 (전기, 수도 등)"),
        ("electricity", "전기"),
        ("plumbing", "배관"),
        ("heating", "난방"),
        ("landlord", "집주인"),
        ("tenant", "세입자"),
        ("rent", "집세"),
        ("lease", "임대차 계약"),
        ("mortgage", "주택 담보 대출"),
        ("laundry", "세탁물"),
        ("detergent", "세제"),
        ("fabric softener", "섬유 유연제"),
        ("closet", "벽장"),
        ("wardrobe", "옷장"),
        ("storage", "저장소"),
        ("tidy", "단정한"),
        ("messy", "지저분한"),
        ("cluttered", "어수선한"),
        ("spacious", "넓은"),
        ("cramped", "비좁은"),
        ("vacuum", "진공청소기, 청소하다"),
        ("dust", "먼지, 먼지를 털다"),
        ("sweep", "쓸다"),
        ("mop", "대걸레질하다"),
        ("scrub", "문질러 닦다"),
        ("polish", "광을 내다"),
        ("organize", "정리하다"),
        ("arrange", "배치하다"),
        
        // 2. Food & Meals (음식과 식사)
        ("meal", "식사"),
        ("breakfast", "아침 식사"),
        ("lunch", "점심 식사"),
        ("dinner", "저녁 식사"),
        ("supper", "저녁 식사"),
        ("snack", "간식"),
        ("beverage", "음료"),
        ("ingredient", "재료"),
        ("recipe", "조리법"),
        ("kitchen", "부엌"),
        ("pantry", "식료품 저장실"),
        ("refrigerator", "냉장고"),
        ("freezer", "냉동고"),
        ("oven", "오븐"),
        ("stove", "가스레인지"),
        ("microwave", "전자레인지"),
        ("consume", "소비하다, 먹다"),
        ("prepare", "준비하다"),
        ("cook", "요리하다"),
        ("bake", "굽다 (빵)"),
        ("roast", "굽다 (고기)"),
        ("grill", "석쇠에 굽다"),
        ("boil", "끓이다"),
        ("fry", "튀기다"),
        ("steam", "찌다"),
        ("chop", "다지다"),
        ("slice", "얇게 썰다"),
        ("dice", "깍둑썰기하다"),
        ("stir", "젓다"),
        ("peel", "껍질을 벗기다"),
        ("nutrition", "영양"),
        ("diet", "식단"),
        ("calorie", "칼로리"),
        ("protein", "단백질"),
        ("carbohydrate", "탄수화물"),
        ("vegetable", "채소"),
        ("fruit", "과일"),
        ("dairy", "유제품"),
        ("grocery", "식료품"),
        ("leftovers", "남은 음식"),
        ("fresh", "신선한"),
        ("stale", "신선하지 않은"),
        ("rotten", "썩은"),
        ("ripe", "익은"),
        ("raw", "날것의"),
        ("cooked", "익힌"),
        ("tasty", "맛있는"),
        ("delicious", "맛있는"),
        ("bland", "맛이 안 나는, 싱거운"),
        ("spicy", "매운"),
        
        // 3. Daily Actions (일상 행동)
        ("wake", "깨다"),
        ("sleep", "자다"),
        ("rest", "쉬다"),
        ("relax", "휴식을 취하다"),
        ("commute", "통근하다"),
        ("bathe", "목욕하다"),
        ("shower", "샤워하다"),
        ("dress", "옷을 입다"),
        ("undress", "옷을 벗다"),
        ("cleanse", "세안하다"),
        ("moisturize", "보습하다"),
        ("commute", "통근하다"),
        ("drive", "운전하다"),
        ("walk", "걷다"),
        ("cycle", "자전거를 타다"),
        ("purchase", "구매하다"),
        ("buy", "사다"),
        ("sell", "팔다"),
        ("spend", "쓰다 (돈, 시간)"),
        ("save", "저축하다, 아끼다"),
        ("afford", "여유가 되다"),
        ("borrow", "빌리다"),
        ("lend", "빌려주다"),
        ("schedule", "일정을 잡다"),
        ("plan", "계획하다"),
        ("arrange", "마련하다"),
        ("postpone", "연기하다"),
        ("cancel", "취소하다"),
        ("contact", "연락하다"),
        ("message", "메시지를 보내다"),
        ("call", "전화하다"),
        ("greet", "인사하다"),
        ("discuss", "논의하다"),
        ("argue", "언쟁하다"),
        ("apologize", "사과하다"),
        ("complain", "불평하다"),
        ("wait", "기다리다"),
        ("hurry", "서두르다"),
        ("lock", "잠그다"),
        ("unlock", "열다"),
        
        // 4. Errands & City (용무 및 도시)
        ("errand", "심부름, 용무"),
        ("bank", "은행"),
        ("account", "계좌"),
        ("deposit", "입금하다"),
        ("withdraw", "인출하다"),
        ("transfer", "이체하다"),
        ("transaction", "거래"),
        ("cash", "현금"),
        ("payment", "결제"),
        ("post office", "우체국"),
        ("mail", "우편"),
        ("package", "소포"),
        ("stamp", "우표"),
        ("pharmacy", "약국"),
        ("drugstore", "약국"),
        ("medicine", "약"),
        ("prescription", "처방전"),
        ("clinic", "병원"),
        ("appointment", "약속"),
        ("reservation", "예약"),
        ("supermarket", "슈퍼마켓"),
        ("bakery", "빵집"),
        ("butcher", "정육점"),
        ("laundromat", "빨래방"),
        ("barber shop", "이발소"),
        ("salon", "미용실"),
        ("library", "도서관"),
        ("transportation", "교통"),
        ("vehicle", "차량"),
        ("passenger", "승객"),
        ("commuter", "통근자"),
        ("pedestrian", "보행자"),
        ("sidewalk", "인도"),
        ("pavement", "보도 (영국)"),
        ("crosswalk", "횡단보도"),
        ("intersection", "교차로"),
        ("traffic", "교통"),
        ("congestion", "교통 체증"),
        ("public transport", "대중교통"),
        ("fare", "요금"),
        
        // 5. Personal Care & Health (개인 관리 및 건강)
        ("health", "건강"),
        ("wellness", "건강"),
        ("hygiene", "위생"),
        ("soap", "비누"),
        ("shampoo", "샴푸"),
        ("conditioner", "린스"),
        ("toothpaste", "치약"),
        ("toothbrush", "칫솔"),
        ("towel", "수건"),
        ("cosmetics", "화장품"),
        ("makeup", "화장"),
        ("perfume", "향수"),
        ("razor", "면도기"),
        ("fitness", "건강, 체력"),
        ("exercise", "운동"),
        ("workout", "운동"),
        ("gym", "체육관"),
        ("symptom", "증상"),
        ("illness", "질병"),
        ("disease", "질병"),
        ("headache", "두통"),
        ("fever", "열"),
        ("cough", "기침"),
        ("cold", "감기"),
        ("flu", "독감"),
        ("fatigue", "피로"),
        ("energy", "에너지"),
        ("rest", "휴식"),
        ("sleep", "수면"),
        ("check-up", "건강 검진"),
        
        // 6. Work & Study (일과 공부)
        ("occupation", "직업"),
        ("profession", "전문직"),
        ("schedule", "일정"),
        ("deadline", "마감 기한"),
        ("assignment", "과제"),
        ("homework", "숙제"),
        ("task", "과업"),
        ("project", "프로젝트"),
        ("meeting", "회의"),
        ("presentation", "발표"),
        ("report", "보고서"),
        ("email", "이메일"),
        ("document", "문서"),
        ("colleague", "동료"),
        ("classmate", "급우"),
        ("study", "공부하다"),
        ("learn", "배우다"),
        ("concentrate", "집중하다"),
        ("focus", "집중하다"),
        ("memorize", "암기하다"),
        ("review", "복습하다"),
        ("revise", "복습하다 (영국)"),
        ("collaborate", "협력하다"),
        ("office", "사무실"),
        ("desk", "책상"),
        ("computer", "컴퓨터"),
        ("laptop", "노트북"),
        ("break", "휴식"),
        ("shift", "교대 근무"),
        ("overtime", "초과 근무"),
        ("busy", "바쁜"),
        ("productive", "생산적인"),
        ("efficient", "효율적인"),
        ("punctual", "시간을 엄수하는"),
        ("diligent", "성실한"),
        
        // 7. Leisure & Social (여가 및 사교)
        ("leisure", "여가"),
        ("hobby", "취미"),
        ("pastime", "취미"),
        ("weekend", "주말"),
        ("holiday", "휴일"),
        ("vacation", "휴가"),
        ("entertainment", "오락"),
        ("movie", "영화"),
        ("theater", "극장"),
        ("music", "음악"),
        ("sport", "스포츠"),
        ("game", "게임"),
        ("park", "공원"),
        ("museum", "박물관"),
        ("restaurant", "레스토랑"),
        ("cafe", "카페"),
        ("pub", "술집"),
        ("socialize", "사교 활동을 하다"),
        ("interact", "상호작용하다"),
        ("chat", "수다 떨다"),
        ("conversation", "대화"),
        ("friend", "친구"),
        ("neighbor", "이웃"),
        ("guest", "손님"),
        ("host", "주인"),
        ("party", "파티"),
        ("celebration", "축하"),
        ("visit", "방문하다"),
        ("invite", "초대하다"),
        ("enjoy", "즐기다"),
        
        // 8. General Concepts (일반 개념)
        ("routine", "일상"),
        ("habit", "습관"),
        ("daily", "매일의"),
        ("regular", "규칙적인"),
        ("usual", "평소의"),
        ("typical", "전형적인"),
        ("normal", "보통의"),
        ("frequent", "잦은"),
        ("rare", "드문"),
        ("occasional", "가끔의"),
        ("convenience", "편의"),
        ("convenient", "편리한"),
        ("necessity", "필수품"),
        ("essential", "필수의"),
        ("priority", "우선순위"),
        ("time", "시간"),
        ("morning", "아침"),
        ("afternoon", "오후"),
        ("evening", "저녁"),
        ("night", "밤"),
        ("early", "이른"),
        ("late", "늦은"),
        ("tired", "피곤한"),
        ("exhausted", "기진맥진한"),
        ("energetic", "활기찬"),
        ("sleepy", "졸린"),
        ("awake", "깨어 있는"),
        ("bored", "지루한"),
        ("calm", "차분한"),
        ("peaceful", "평화로운"),
    ]
}

struct MockEmotionWords {
    static let data: [(String, String)] = [
        ("happy", "행복한"),
        ("glad", "기쁜"),
        ("pleased", "기쁜, 만족하는"),
        ("delighted", "아주 기쁜"),
        ("joyful", "매우 기쁜"),
        ("cheerful", "쾌활한, 발랄한"),
        ("merry", "명랑한, 즐거운"),
        ("content", "만족하는"),
        ("satisfied", "만족한"),
        ("elated", "의기양양한, 매우 기뻐하는"),
        ("overjoyed", "매우 기뻐하는"),
        ("thrilled", "아주 흥분한, 신이 난"),
        ("ecstatic", "황홀해하는, 열광하는"),
        ("upbeat", "낙관적인, 쾌활한"),
        ("positive", "긍정적인"),
        ("optimistic", "낙관적인"),
        ("enthusiastic", "열광적인, 열정적인"),
        ("excited", "신이 난, 흥분한"),
        ("lively", "활기 넘치는"),
        ("energetic", "활기 넘치는"),
        ("playful", "장난기 많은, 농담조의"),
        ("blissful", "더없이 행복한"),
        ("grateful", "감사하는"),
        ("thankful", "고마워하는"),
        ("relieved", "안도하는"),
        ("calm", "차분한"),
        ("peaceful", "평화로운"),
        ("serene", "고요한, 평온한"),
        ("relaxed", "편안한"),
        ("comfortable", "편안한"),
        ("happiness", "행복"),
        ("joy", "기쁨"),
        ("delight", "큰 기쁨"),
        ("pleasure", "기쁨, 즐거움"),
        ("satisfaction", "만족"),
        ("contentment", "만족(감)"),
        ("optimism", "낙관주의"),
        ("enthusiasm", "열정"),
        ("excitement", "흥분, 신남"),
        ("relief", "안도, 안심"),
        ("gratitude", "감사"),
        ("enjoy", "즐기다"),
        ("appreciate", "고마워하다, 진가를 알다"),
        ("celebrate", "축하하다"),
        
        // 2. Sadness & Grief (슬픔과 비탄)
        ("sad", "슬픈"),
        ("unhappy", "불행한, 슬픈"),
        ("miserable", "비참한"),
        ("depressed", "우울한"),
        ("gloomy", "우울한, 침울한"),
        ("glum", "침울한"),
        ("down", "우울한, 기분이 안 좋은"),
        ("blue", "우울한"),
        ("melancholy", "우울한"),
        ("sorrowful", "아주 슬픈, 비탄에 잠긴"),
        ("heartbroken", "비통해하는"),
        ("devastated", "엄청난 충격을 받은"),
        ("upset", "속상한, 마음이 상한"),
        ("disappointed", "실망한"),
        ("discouraged", "낙담한"),
        ("disheartened", "낙담한"),
        ("pessimistic", "비관적인"),
        ("negative", "부정적인"),
        ("hopeless", "희망이 없는"),
        ("desperate", "절망적인, 자포자기한"),
        ("lonely", "외로운"),
        ("isolated", "고립된"),
        ("sadness", "슬픔"),
        ("grief", "비탄, 큰 슬픔"),
        ("sorrow", "슬픔, 비애"),
        ("misery", "비참함"),
        ("depression", "우울증, 우울함"),
        ("despair", "절망"),
        ("disappointment", "실망"),
        ("loneliness", "외로움"),
        ("grieve", "비통해하다"),
        ("mourn", "애도하다"),
        ("weep", "울다"),
        ("cry", "울다"),
        ("regret", "후회하다"),
        
        // 3. Anger & Frustration (분노와 좌절)
        ("angry", "화난"),
        ("mad", "화난 (비격식)"),
        ("furious", "격노한"),
        ("irate", "격노한"),
        ("enraged", "격분한"),
        ("livid", "격노한"),
        ("cross", "화가 난 (주로 영국)"),
        ("annoyed", "짜증이 난"),
        ("irritated", "짜증이 난"),
        ("frustrated", "좌절한, 불만스러운"),
        ("agitated", "불안해하는, 동요된"),
        ("resentful", "분개하는"),
        ("bitter", "억울해하는, 쓰라린"),
        ("offended", "기분이 상한, 불쾌한"),
        ("indignant", "분개한"),
        ("impatient", "짜증 난, 조바심 내는"),
        ("hostile", "적대적인"),
        ("aggressive", "공격적인"),
        ("grumpy", "툴툴거리는, 성격이 나쁜"),
        ("sulky", "뾰로통한, 부루퉁한"),
        ("moody", "기분 변화가 심한"),
        ("anger", "분노, 화"),
        ("rage", "격노"),
        ("fury", "분노, 격분"),
        ("wrath", "분노 (격식)"),
        ("frustration", "좌절(감)"),
        ("annoyance", "짜증"),
        ("irritation", "짜증"),
        ("resentment", "분개"),
        ("bitterness", "쓰라림, 원망"),
        ("impatience", "조바심, 성급함"),
        ("hatred", "증오"),
        ("hate", "증오하다"),
        ("detest", "몹시 싫어하다"),
        ("despise", "경멸하다"),
        ("loathe", "혐오하다"),
        
        // 4. Fear & Anxiety (두려움과 불안)
        ("afraid", "두려워하는"),
        ("scared", "무서워하는"),
        ("frightened", "겁먹은, 무서워하는"),
        ("terrified", "몹시 무서워하는"),
        ("horrified", "겁에 질린, 충격받은"),
        ("petrified", "극도로 무서워하는"),
        ("anxious", "불안한, 걱정하는"),
        ("worried", "걱정하는"),
        ("concerned", "걱정하는"),
        ("apprehensive", "걱정되는, 불안한"),
        ("nervous", "불안한, 초조한"),
        ("tense", "긴장한"),
        ("stressed", "스트레스를 받는"),
        ("stressed out", "스트레스가 심한"),
        ("panicky", "공황 상태에 빠진"),
        ("insecure", "불안정한, 자신이 없는"),
        ("uneasy", "불안한, 불편한"),
        ("dreadful", "끔찍한, 무시무시한"),
        ("fear", "두려움, 공포"),
        ("fright", "공포, 경악"),
        ("terror", "극심한 공포"),
        ("horror", "공포, 전율"),
        ("anxiety", "불안, 염려"),
        ("worry", "걱정"),
        ("concern", "걱정, 우려"),
        ("tension", "긴장"),
        ("stress", "스트레스"),
        ("panic", "공황"),
        ("insecurity", "불안감"),
        ("dread", "공포, 불안"),
        ("fear", "두려워하다"),
        ("worry", "걱정하다"),
        
        // 5. Surprise & Shock (놀람과 충격)
        ("surprised", "놀란"),
        ("shocked", "충격받은"),
        ("astonished", "몹시 놀란"),
        ("amazed", "(경이로워서) 몹시 놀란"),
        ("astounded", "경악한, 몹시 놀란"),
        ("stunned", "(멍할 정도로) 놀란"),
        ("startled", "깜짝 놀란"),
        ("bewildered", "어리둥절한, 당혹한"),
        ("confused", "혼란스러운"),
        ("puzzled", "어리둥절한"),
        ("perplexed", "당혹스러운"),
        ("flabbergasted", "어안이 벙벙한 (비격식)"),
        ("surprise", "놀람"),
        ("shock", "충격"),
        ("astonishment", "놀람"),
        ("amazement", "놀람"),
        ("confusion", "혼란"),
        ("bewilderment", "당혹함"),
        ("surprise", "놀라게 하다"),
        ("shock", "충격을 주다"),
        ("amaze", "몹시 놀라게 하다"),
        ("astonish", "몹시 놀라게 하다"),
        ("startle", "깜짝 놀라게 하다"),
        ("confuse", "혼란스럽게 하다"),
        
        // 6. Interest & Curiosity (관심과 호기심)
        ("interested", "관심 있는"),
        ("curious", "궁금한, 호기심 많은"),
        ("keen", "열심인, 관심이 많은"),
        ("eager", "열망하는"),
        ("fascinated", "매료된"),
        ("captivated", "마음이 사로잡힌"),
        ("intrigued", "아주 흥미로워하는"),
        ("engaged", "몰두한, 관심이 쏠린"),
        ("absorbed", "몰두한"),
        ("motivated", "동기가 부여된"),
        ("inspired", "영감을 받은"),
        ("passionate", "열정적인"),
        ("interest", "관심, 흥미"),
        ("curiosity", "호기심"),
        ("eagerness", "열망"),
        ("fascination", "매혹"),
        ("motivation", "동기 부여"),
        ("inspiration", "영감"),
        ("passion", "열정"),
        
        // 7. Confidence & Pride (자신감과 자부심)
        ("confident", "자신감 있는"),
        ("self-confident", "자신감이 있는"),
        ("sure", "확신하는"),
        ("certain", "확신하는"),
        ("secure", "안심하는, 자신감 있는"),
        ("self-assured", "자신감에 찬"),
        ("proud", "자랑스러운"),
        ("courageous", "용감한"),
        ("brave", "용감한"),
        ("bold", "대담한"),
        ("determined", "단호한, 결의에 찬"),
        ("confidence", "자신감"),
        ("assurance", "확신"),
        ("self-esteem", "자존감"),
        ("pride", "자부심, 자존심"),
        ("courage", "용기"),
        ("bravery", "용기"),
        ("determination", "결의, 투지"),
        ("believe in", "...을 믿다"),
        ("trust", "신뢰하다"),
        
        // 8. Shame & Embarrassment (수치심과 당황)
        ("ashamed", "부끄러운, 수치스러운"),
        ("embarrassed", "당황스러운, 쪽팔린"),
        ("humiliated", "굴욕감을 느낀"),
        ("guilty", "죄책감을 느끼는"),
        ("awkward", "어색한, 곤란한"),
        ("uncomfortable", "불편한"),
        ("shy", "수줍어하는"),
        ("bashful", "수줍음을 타는"),
        ("self-conscious", "남의 시선을 의식하는"),
        ("inferior", "열등감을 느끼는"),
        ("shame", "수치심, 창피"),
        ("embarrassment", "당황, 어색함"),
        ("humiliation", "굴욕, 창피"),
        ("guilt", "죄책감"),
        ("awkwardness", "어색함"),
        ("shyness", "수줍음"),
        ("insecurity", "불안감"),
        ("regret", "후회"),
        
        // 9. Social Emotions (사회적 감정)
        ("friendly", "다정한, 친절한"),
        ("kind", "친절한"),
        ("caring", "배려하는"),
        ("loving", "애정 어린"),
        ("affectionate", "다정한"),
        ("sympathetic", "동정하는, 공감하는"),
        ("empathetic", "공감하는"),
        ("compassionate", "연민 어린"),
        ("considerate", "사려 깊은"),
        ("thoughtful", "배려심 있는"),
        ("generous", "관대한"),
        ("polite", "공손한"),
        ("respectful", "존중하는"),
        ("trusting", "신뢰하는"),
        ("jealous", "질투하는"),
        ("envious", "부러워하는"),
        ("suspicious", "의심하는"),
        ("distrustful", "불신하는"),
        ("lonely", "외로운"),
        ("isolated", "고립된"),
        ("left out", "소외된"),
        ("rejected", "거부당한"),
        ("love", "사랑"),
        ("affection", "애정"),
        ("kindness", "친절"),
        ("sympathy", "동정"),
        ("empathy", "공감"),
        ("compassion", "연민"),
        ("generosity", "관대함"),
        ("respect", "존경"),
        ("trust", "신뢰"),
        ("jealousy", "질투"),
        ("envy", "부러움, 선망"),
        ("suspicion", "의심"),
        ("loneliness", "외로움"),
        
        // 10. Indifference & Boredom (무관심과 지루함)
        ("bored", "지루한"),
        ("uninterested", "무관심한"),
        ("indifferent", "무관심한"),
        ("apathetic", "무관심한, 냉담한"),
        ("dull", "지루한"),
        ("tedious", "지루한"),
        ("monotonous", "단조로운"),
        ("weary", "지친, 싫증 난"),
        ("tired", "피곤한"),
        ("exhausted", "기진맥진한"),
        ("fatigued", "피로한"),
        ("drained", "진이 빠진"),
        ("lethargic", "무기력한"),
        ("listless", "무기력한"),
        ("boredom", "지루함"),
        ("indifference", "무관심"),
        ("apathy", "무관심, 냉담"),
        ("monotony", "단조로움"),
        ("weariness", "피로, 권태"),
        ("tiredness", "피곤함"),
        ("fatigue", "피로"),
        ("exhaustion", "탈진, 기진맥진"),
        
        // 11. Mixed & Other Emotions (복합적 및 기타 감정)
        ("ambivalent", "양가감정의 (반대 감정이 공존)"),
        ("nostalgic", "향수를 느끼는"),
        ("sentimental", "감상적인"),
        ("cautious", "조심스러운"),
        ("hesitant", "망설이는"),
        ("reluctant", "꺼리는, 마지못해 하는"),
        ("smug", "의기양양한, 우쭐해하는"),
        ("arrogant", "거만한"),
        ("humbled", "겸허해진"),
        ("grateful", "감사하는"),
        ("hopeful", "희망에 찬"),
        ("moved", "감동받은"),
        ("touched", "감동받은"),
        ("overwhelmed", "압도된 (감당하기 힘든)"),
        ("vulnerable", "취약한, 상처받기 쉬운"),
        ("defensive", "방어적인"),
        ("nostalgia", "향수"),
        ("hope", "희망"),
    ]
}


struct MockBusinessWords {
    static let data: [(String, String)] = [
        ("office", "사무실"),
        ("workplace", "직장"),
        ("cubicle", "칸막이 사무실"),
        ("open-plan office", "개방형 사무실"),
        ("equipment", "장비, 설비"),
        ("stationery", "문구류"),
        ("document", "문서"),
        ("file", "파일"),
        ("folder", "폴더"),
        ("briefcase", "서류 가방"),
        ("memo", "메모"),
        ("report", "보고서"),
        ("deadline", "마감 기한"),
        ("task", "과업, 임무"),
        ("assignment", "과제, 임무"),
        ("project", "프로젝트"),
        ("workload", "업무량"),
        ("overtime", "초과 근무"),
        ("shift", "교대 근무"),
        ("telecommuting", "재택근무"),
        ("remote work", "원격 근무"),
        ("flexible hours", "유연 근무 시간"),
        ("productivity", "생산성"),
        ("efficiency", "효율성"),
        ("policy", "정책"),
        ("procedure", "절차"),
        ("guideline", "지침"),
        ("company culture", "기업 문화"),
        ("bulletin board", "게시판"),
        ("intranet", "인트라넷 (사내망)"),
        ("copier", "복사기"),
        ("printer", "프린터"),
        ("shredder", "문서 세단기"),
        ("break room", "휴게실"),
        ("workspace", "작업 공간"),
        ("business trip", "출장"),
        ("expense report", "비용 보고서"),
        
        // 2. Roles & People (직책 및 사람)
        ("employee", "직원, 피고용인"),
        ("employer", "고용주"),
        ("staff", "직원 (전체)"),
        ("personnel", "인원, 직원들"),
        ("workforce", "노동력, 전 직원"),
        ("manager", "관리자, 매니저"),
        ("supervisor", "감독자, 관리자"),
        ("director", "이사, 임원"),
        ("executive", "경영진, 임원"),
        ("CEO", "최고 경영자 (Chief Executive Officer)"),
        ("CFO", "최고 재무 책임자 (Chief Financial Officer)"),
        ("founder", "설립자"),
        ("colleague", "동료"),
        ("coworker", "동료"),
        ("associate", "동료, 제휴자"),
        ("partner", "파트너, 동업자"),
        ("client", "고객 (주로 서비스)"),
        ("customer", "고객 (주로 상품)"),
        ("consumer", "소비자"),
        ("supplier", "공급업체"),
        ("vendor", "판매업체, 행상"),
        ("competitor", "경쟁자"),
        ("rival", "경쟁자"),
        ("applicant", "지원자"),
        ("candidate", "후보자"),
        ("recruit", "신입사원"),
        ("intern", "인턴"),
        ("trainee", "훈련생, 수습사원"),
        ("mentor", "멘토"),
        ("consultant", "컨설턴트"),
        ("representative", "대표, 대리인"),
        ("shareholder", "주주"),
        ("stakeholder", "이해관계자"),
        ("board of directors", "이사회"),
        ("receptionist", "접수원"),
        ("assistant", "비서, 보조원"),
        ("entrepreneur", "기업가"),
        
        // 3. Finance & Economics (재무 및 경제)
        ("finance", "재무, 재정"),
        ("budget", "예산"),
        ("salary", "급여 (월급/연봉)"),
        ("wage", "임금 (시급/주급)"),
        ("income", "소득"),
        ("revenue", "수익, 총매출"),
        ("turnover", "총매출액"),
        ("profit", "이익, 순수익"),
        ("loss", "손실"),
        ("margin", "마진, 이익률"),
        ("cost", "비용, 원가"),
        ("expense", "지출, 비용"),
        ("overhead", "간접비, 경상비"),
        ("investment", "투자"),
        ("capital", "자본"),
        ("asset", "자산"),
        ("liability", "부채"),
        ("debt", "빚, 부채"),
        ("loan", "대출"),
        ("interest", "이자"),
        ("mortgage", "담보대출"),
        ("stock", "주식, 재고"),
        ("share", "주식, 지분"),
        ("dividend", "배당금"),
        ("stock market", "주식 시장"),
        ("recession", "경기 침체"),
        ("inflation", "인플레이션 (물가 상승)"),
        ("tax", "세금"),
        ("invoice", "송장, 청구서"),
        ("receipt", "영수증"),
        ("refund", "환불"),
        ("payment", "지불"),
        ("transaction", "거래"),
        ("account", "계좌, 회계"),
        ("bankrupt", "파산한"),
        ("bankruptcy", "파산"),
        ("audit", "회계 감사"),
        ("accountant", "회계사"),
        ("financial statement", "재무 제표"),
        ("balance sheet", "대차 대조표"),
        ("cash flow", "현금 흐름"),
        ("forecast", "예측"),
        ("projection", "예상, 추정"),
        ("currency", "통화"),
        ("exchange rate", "환율"),
        ("quarter", "분기 (1/4)"),
        ("fiscal year", "회계 연도"),
        ("subsidy", "보조금"),
        ("grant", "보조금"),
        
        // 4. Marketing & Sales (마케팅 및 영업)
        ("marketing", "마케팅"),
        ("sales", "영업, 매출"),
        ("advertisement", "광고 (개별)"),
        ("advertising", "광고 (행위, 산업)"),
        ("commercial", "상업 광고 (TV, 라디오)"),
        ("campaign", "캠페인"),
        ("promotion", "홍보, 승진"),
        ("brand", "브랜드"),
        ("logo", "로고"),
        ("slogan", "슬로건"),
        ("market research", "시장 조사"),
        ("survey", "설문 조사"),
        ("questionnaire", "설문지"),
        ("target audience", "목표 고객"),
        ("consumer behavior", "소비자 행동"),
        ("demographics", "인구 통계"),
        ("public relations", "홍보 (PR)"),
        ("press release", "보도 자료"),
        ("sponsorship", "후원"),
        ("brochure", "브로슈어"),
        ("flyer", "전단지"),
        ("leaflet", "전단지"),
        ("billboard", "광고판"),
        ("product", "제품, 상품"),
        ("service", "서비스"),
        ("launch", "출시"),
        ("release", "출시, 발표"),
        ("price", "가격"),
        ("discount", "할인"),
        ("negotiation", "협상"),
        ("deal", "거래"),
        ("wholesale", "도매"),
        ("retail", "소매"),
        ("distributor", "유통업체"),
        ("customer service", "고객 서비스"),
        ("feedback", "피드백"),
        ("complaint", "불만, 항의"),
        ("inquiry", "문의"),
        
        // 5. Meetings & Communication (회의 및 소통)
        ("meeting", "회의"),
        ("conference", "컨퍼런스, 대회의"),
        ("seminar", "세미나"),
        ("workshop", "워크숍"),
        ("presentation", "발표"),
        ("speech", "연설"),
        ("agenda", "안건, 의제"),
        ("minutes", "회의록"),
        ("participant", "참가자"),
        ("attendee", "참석자"),
        ("chairperson", "의장"),
        ("host", "주최자"),
        ("venue", "장소 (행사)"),
        ("schedule", "일정"),
        ("appointment", "약속 (업무, 병원 등)"),
        ("discussion", "토론"),
        ("debate", "토론"),
        ("brainstorm", "브레인스토밍"),
        ("proposal", "제안"),
        ("suggestion", "제안"),
        ("objective", "목표"),
        ("strategy", "전략"),
        ("consensus", "합의"),
        ("agreement", "동의, 합의"),
        ("negotiate", "협상하다"),
        ("clarify", "명확히 하다"),
        ("summarize", "요약하다"),
        ("visual aid", "시각 자료"),
        ("handout", "유인물"),
        ("projector", "프로젝터"),
        ("conference call", "전화 회의"),
        ("video conference", "화상 회의"),
        ("follow-up", "후속 조치"),
        ("postpone", "연기하다"),
        ("cancel", "취소하다"),
        ("reschedule", "일정을 변경하다"),
        
        // 6. Company Structure & Operations (회사 구조 및 운영)
        ("company", "회사"),
        ("firm", "회사 (주로 법률, 회계 등 전문직)"),
        ("corporation", "법인, 기업"),
        ("enterprise", "기업, 사업체"),
        ("organization", "조직, 단체"),
        ("industry", "산업"),
        ("sector", "부문, 분야"),
        ("department", "부서"),
        ("division", "부서, 사업부"),
        ("headquarters", "본사 (HQ)"),
        ("branch", "지점"),
        ("subsidiary", "자회사"),
        ("parent company", "모회사"),
        ("merger", "합병"),
        ("acquisition", "인수"),
        ("M&A", "인수 합병"),
        ("partnership", "파트너십, 동업"),
        ("joint venture", "합작 투자"),
        ("small business", "중소기업 (SME)"),
        ("startup", "스타트업"),
        ("multinational", "다국적 기업"),
        ("non-profit", "비영리 단체"),
        ("management", "경영진, 관리"),
        ("administration", "행정, 관리"),
        ("operations", "운영"),
        ("logistics", "물류"),
        ("supply chain", "공급망"),
        ("inventory", "재고"),
        ("warehouse", "창고"),
        ("production", "생산"),
        ("manufacturing", "제조"),
        ("factory", "공장"),
        ("R&D", "연구 개발 (Research and Development)"),
        ("Human Resources", "인사과 (HR)"),
        ("IT department", "IT 부서 (Information Technology)"),
        ("headcount", "인원수"),
        
        // 7. Legal & Contracts (법률 및 계약)
        ("contract", "계약"),
        ("agreement", "합의, 계약서"),
        ("terms", "조건, 조항"),
        ("conditions", "조건"),
        ("clause", "조항"),
        ("regulation", "규정"),
        ("law", "법률"),
        ("legal", "법적인"),
        ("lawsuit", "소송"),
        ("attorney", "변호사"),
        ("lawyer", "변호사"),
        ("copyright", "저작권"),
        ("patent", "특허"),
        ("trademark", "상표"),
        ("confidential", "기밀의"),
        ("signature", "서명"),
        ("violation", "위반"),
        ("breach of contract", "계약 위반"),
        ("negotiate", "협상하다"),
        ("draft", "초안을 작성하다"),
        
        // 8. Employment & HR (고용 및 인사)
        ("recruitment", "채용"),
        ("hire", "고용하다"),
        ("fire", "해고하다"),
        ("dismiss", "해고하다"),
        ("layoff", "정리해고"),
        ("resign", "사임하다"),
        ("quit", "그만두다"),
        ("retirement", "은퇴"),
        ("resume", "이력서 (미국)"),
        ("CV", "이력서 (Curriculum Vitae, 영국/학계)"),
        ("cover letter", "자기소개서"),
        ("application", "지원서"),
        ("interview", "면접"),
        ("job offer", "채용 제안"),
        ("contract", "고용 계약서"),
        ("salary", "급여"),
        ("promotion", "승진"),
        ("demotion", "강등"),
        ("training", "교육, 훈련"),
        ("development", "개발"),
        ("performance", "성과, 실적"),
        ("evaluation", "평가"),
        ("assessment", "평가"),
        ("benefit", "복리후생"),
        ("pension", "연금"),
        ("insurance", "보험"),
        ("leave", "휴가"),
        ("sick leave", "병가"),
        ("maternity leave", "출산 휴가"),
        ("annual leave", "연차 휴가"),
        
        // 9. Business Actions (비즈니스 행위)
        ("manage", "관리하다"),
        ("organize", "조직하다"),
        ("plan", "계획하다"),
        ("execute", "실행하다"),
        ("implement", "시행하다"),
        ("analyze", "분석하다"),
        ("evaluate", "평가하다"),
        ("assess", "평가하다"),
        ("approve", "승인하다"),
        ("reject", "거절하다"),
        ("propose", "제안하다"),
        ("invest", "투자하다"),
        ("develop", "개발하다"),
        ("innovate", "혁신하다"),
        ("compete", "경쟁하다"),
        ("collaborate", "협력하다"),
        ("communicate", "의사소통하다"),
        ("supervise", "감독하다"),
        ("lead", "이끌다"),
        ("delegate", "위임하다"),
        ("participate", "참여하다"),
        ("attend", "참석하다"),
        ("establish", "설립하다"),
        ("expand", "확장하다"),
        ("downsize", "규모를 축소하다"),
        ("outsource", "외주를 주다"),
        ("prioritize", "우선순위를 정하다"),
    ]
}

struct MockTravelWords {
    static let data: [(String, String)] = [
            // 1. Accommodation (숙박)
            ("accommodation", "숙소"),
            ("hotel", "호텔"),
            ("hostel", "호스텔"),
            ("motel", "모텔"),
            ("inn", "여관"),
            ("lodge", "산장, 오두막"),
            ("resort", "휴양지, 리조트"),
            ("villa", "빌라, 별장"),
            ("apartment", "아파트"),
            ("suite", "스위트룸"),
            ("guesthouse", "게스트하우스"),
            ("B&B", "B&B (아침 식사 제공 민박)"),
            ("dormitory", "기숙사형 침실"),
            ("reception", "접수처, 리셉션"),
            ("front desk", "프런트 데스크"),
            ("lobby", "로비"),
            ("amenities", "편의 시설"),
            ("facilities", "시설"),
            ("reservation", "예약"),
            ("booking", "예약"),
            ("vacancy", "빈 방"),
            ("check-in", "체크인"),
            ("check-out", "체크아웃"),
            ("key card", "카드 키"),
            ("concierge", "콘시어지"),
            ("bellboy", "벨보이"),
            ("housekeeping", "객실 관리"),
            ("room service", "룸서비스"),
            ("single room", "1인실"),
            ("double room", "2인실 (더블 침대 1개)"),
            ("twin room", "2인실 (싱글 침대 2개)"),
            ("en-suite", "객실 내 딸린 욕실"),
            ("balcony", "발코니"),
            ("view", "전망"),
            ("complimentary", "무료의"),
            ("minibar", "미니바"),
            ("valet", "발레 파킹, 객실 담당 직원"),
            ("laundry service", "세탁 서비스"),
            ("shuttle bus", "셔틀 버스"),
            ("all-inclusive", "모든 비용이 포함된"),

            // 2. Transportation (교통)
            ("transportation", "교통, 운송"),
            ("vehicle", "차량, 탈것"),
            ("public transport", "대중교통"),
            ("fare", "요금"),
            ("ticket", "표, 티켓"),
            ("one-way ticket", "편도 티켓"),
            ("round trip", "왕복 여행"),
            ("return ticket", "왕복 티켓"),
            ("commute", "통근하다"),
            ("passenger", "승객"),
            ("driver", "운전사"),
            ("pilot", "조종사"),
            ("captain", "선장, 기장"),
            ("platform", "플랫폼"),
            ("station", "역, 정류장"),
            ("terminal", "터미널"),
            ("port", "항구"),
            ("harbor", "항구, 정박지"),
            ("quay", "부두, 선창"),
            ("pier", "부두"),
            ("domestic flight", "국내선"),
            ("international flight", "국제선"),
            ("direct flight", "직항편"),
            ("layover", "경유, 환승 (대기 시간)"),
            ("stopover", "단기 체류 (경유지에서)"),
            ("transfer", "환승하다"),
            ("connect (flight)", "연결편, 환승하다"),
            ("on board", "탑승한"),
            ("embark", "승선하다, 탑승하다"),
            ("disembark", "하선하다, 내리다"),
            ("vessel", "선박, 배"),
            ("ferry", "페리, 연락선"),
            ("cruise", "크루즈, 유람선"),
            ("yacht", "요트"),
            ("subway", "지하철"),
            ("underground", "지하철 (영국)"),
            ("metro", "지하철 (유럽 등)"),
            ("tram", "전차"),
            ("coach", "장거리 버스"),
            ("cab", "택시"),
            ("taxi rank", "택시 승강장"),
            ("rental", "대여, 렌트"),
            ("junction", "교차로, 분기점"),
            ("roundabout", "로터리, 원형 교차로"),
            ("traffic jam", "교통 체증"),
            ("congestion", "혼잡, 정체"),
            ("highway", "고속도로"),
            ("motorway", "고속도로 (영국)"),
            ("route", "경로"),
            ("pedestrian", "보행자"),

            // 3. Booking & Reservations (예약)
            ("book", "예약하다"),
            ("reserve", "예약하다"),
            ("confirm", "확인하다"),
            ("confirmation", "확인, 확약"),
            ("cancel", "취소하다"),
            ("cancellation", "취소"),
            ("fully booked", "예약이 꽉 찬"),
            ("available", "이용 가능한"),
            ("availability", "이용 가능성"),
            ("deposit", "보증금, 예약금"),
            ("refund", "환불"),
            ("non-refundable", "환불 불가"),
            ("itinerary", "여행 일정표"),
            ("schedule", "일정"),
            ("online booking", "온라인 예약"),
            ("travel agent", "여행사 직원"),
            ("travel agency", "여행사"),
            ("package tour", "패키지 여행"),
            ("tour operator", "여행사"),
            ("voucher", "교환권, 바우처"),
            ("e-ticket", "전자 항공권"),
            ("boarding pass", "탑승권"),
            ("payment", "결제"),
            ("credit card", "신용카드"),
            ("debit card", "직불카드"),
            ("fee", "수수료, 요금"),
            ("charge", "요금, 청구하다"),
            ("discount", "할인"),
            ("coupon", "쿠폰"),
            ("policy", "정책, 방침"),

            // 4. At the Airport (공항에서)
            ("airport", "공항"),
            ("airline", "항공사"),
            ("flight", "항공편"),
            ("check-in counter", "체크인 카운터"),
            ("self check-in", "셀프 체크인"),
            ("luggage", "수하물 (영국)"),
            ("baggage", "수하물 (미국)"),
            ("suitcase", "여행 가방"),
            ("carry-on", "기내 휴대용 수하물"),
            ("hand luggage", "기내 휴대용 수하물"),
            ("checked baggage", "부치는 짐"),
            ("baggage claim", "수하물 찾는 곳"),
            ("carousel", "수하물 컨베이어 벨트"),
            ("excess baggage", "초과 수하물"),
            ("overweight", "중량 초과"),
            ("scale", "저울"),
            ("trolley", "카트"),
            ("cart", "카트"),
            ("security check", "보안 검색"),
            ("metal detector", "금속 탐지기"),
            ("passport control", "여권 심사"),
            ("immigration", "출입국 심사"),
            ("customs", "세관"),
            ("declare", "신고하다"),
            ("nothing to declare", "신고할 물건 없음"),
            ("duty-free", "면세"),
            ("departure lounge", "출발 라운지"),
            ("gate", "탑승구"),
            ("board", "탑승하다"),
            ("boarding", "탑승"),
            ("final call", "최종 탑승 안내"),
            ("on time", "정시에"),
            ("delayed", "지연된"),
            ("cancelled", "취소된"),
            ("arrival", "도착"),
            ("departure", "출발"),
            ("aisle seat", "복도 쪽 좌석"),
            ("window seat", "창가 좌석"),
            ("middle seat", "가운데 좌석"),
            ("seatbelt", "좌석 벨트"),
            ("fasten", "매다, 고정하다"),
            ("cabin crew", "객실 승무원"),
            ("flight attendant", "객실 승무원"),
            ("take off", "이륙"),
            ("land", "착륙하다"),
            ("landing", "착륙"),
            ("turbulence", "난기류"),
            ("jet lag", "시차증"),
            ("long-haul flight", "장거리 비행"),

            // 5. Directions & Getting Around (길찾기 및 이동)
            ("map", "지도"),
            ("guidebook", "가이드북"),
            ("GPS", "GPS, 위성 위치 확인 시스템"),
            ("compass", "나침반"),
            ("navigate", "길을 찾다, 항해하다"),
            ("navigation", "길찾기, 항법"),
            ("direction", "방향"),
            ("avenue", "대로"),
            ("street", "거리"),
            ("road", "길, 도로"),
            ("lane", "차선, 좁은 길"),
            ("alley", "골목"),
            ("boulevard", "대로"),
            ("highway", "고속도로"),
            ("intersection", "교차로"),
            ("crossroads", "사거리"),
            ("traffic light", "신호등"),
            ("signpost", "표지판"),
            ("landmark", "주요 지형지물, 랜드마크"),
            ("turn left", "좌회전"),
            ("turn right", "우회전"),
            ("go straight", "직진하다"),
            ("opposite", "맞은편의"),
            ("adjacent", "인접한"),
            ("nearby", "가까운"),
            ("within walking distance", "걸어갈 수 있는 거리 내에"),
            ("far", "먼"),
            ("public square", "광장"),
            ("suburb", "교외, 근교"),
            ("downtown", "시내 중심가"),

            // 6. Sightseeing & Activities (관광 및 활동)
            ("sightseeing", "관광"),
            ("tourist", "관광객"),
            ("tour", "관광, 투어"),
            ("guided tour", "가이드가 있는 투어"),
            ("tour guide", "관광 가이드"),
            ("attraction", "관광 명소"),
            ("destination", "목적지"),
            ("monument", "기념물"),
            ("statue", "동상"),
            ("museum", "박물관"),
            ("gallery", "미술관"),
            ("exhibition", "전시회"),
            ("palace", "궁전"),
            ("castle", "성"),
            ("cathedral", "대성당"),
            ("church", "교회"),
            ("temple", "사원, 절"),
            ("ruins", "유적, 폐허"),
            ("ancient", "고대의"),
            ("historic", "역사적인, 역사적으로 중요한"),
            ("historical", "역사의"),
            ("architecture", "건축"),
            ("fountain", "분수"),
            ("park", "공원"),
            ("national park", "국립 공원"),
            ("botanical garden", "식물원"),
            ("zoo", "동물원"),
            ("aquarium", "수족관"),
            ("theme park", "테마파크"),
            ("amusement park", "놀이공원"),
            ("souvenir", "기념품"),
            ("gift shop", "기념품 가게"),
            ("scenery", "풍경"),
            ("viewpoint", "전망대"),
            ("landscape", "풍경, 경치"),
            ("countryside", "시골"),
            ("cityscape", "도시 풍경"),
            ("explore", "탐험하다"),
            ("discover", "발견하다"),
            ("wander", "거닐다, 헤매다"),
            ("hike", "하이킹하다"),
            ("trek", "트레킹하다"),
            ("climb", "오르다"),
            ("swim", "수영하다"),
            ("sunbathe", "일광욕하다"),
            ("relax", "쉬다"),
            ("unwind", "긴장을 풀다"),
            ("adventure", "모험"),
            ("experience", "경험"),
            ("activity", "활동"),
            ("leisure", "여가"),
            ("recreation", "레크리에이션, 오락"),
            ("entertainment", "엔터테인먼트, 오락"),
            ("festival", "축제"),
            ("parade", "퍼레이드, 행진"),
            ("performance", "공연"),
            ("concert", "콘서트"),
            ("theatre", "극장"),
            ("admission", "입장료, 입장"),
            ("entrance fee", "입장료"),

            // 7. Food & Dining (음식 및 식사)
            ("restaurant", "레스토랑, 식당"),
            ("cafe", "카페"),
            ("cafeteria", "카페테리아 (구내 식당)"),
            ("diner", "작은 식당"),
            ("bistro", "비스트로 (작은 식당, 바)"),
            ("pub", "펍, 대중 술집"),
            ("bar", "바, 술집"),
            ("menu", "메뉴"),
            ("appetizer", "전채 요리"),
            ("starter", "시작 요리"),
            ("main course", "메인 코스, 주 요리"),
            ("entrée", "메인 요리 (미국) / 전채 요리 (영국)"),
            ("side dish", "곁들임 요리"),
            ("dessert", "디저트, 후식"),
            ("beverage", "음료"),
            ("drink", "음료, 마시다"),
            ("waiter", "웨이터"),
            ("waitress", "웨이트리스"),
            ("server", "종업원"),
            ("chef", "주방장, 요리사"),
            ("order", "주문하다"),
            ("bill", "계산서 (영국)"),
            ("check", "계산서 (미국)"),
            ("tip", "팁"),
            ("service charge", "봉사료"),
            ("cuisine", "요리, 요리법"),
            ("local food", "현지 음식"),
            ("specialty", "특산물, 전문 요리"),
            ("street food", "길거리 음식"),
            ("delicious", "맛있는"),
            ("tasty", "맛있는"),
            ("spicy", "매운"),
            ("sweet", "단"),
            ("sour", "신"),
            ("bitter", "쓴"),
            ("salty", "짠"),
            ("fresh", "신선한"),
            ("vegetarian", "채식주의자"),
            ("vegan", "비건 (완전 채식주의자)"),
            ("allergy", "알레르기"),

            // 8. General Travel (일반 여행)
            ("travel", "여행"),
            ("journey", "여정, 여행 (특히 긴)"),
            ("trip", "여행 (비교적 짧은)"),
            ("voyage", "항해, 긴 여행"),
            ("expedition", "탐험, 원정"),
            ("holiday", "휴가 (영국)"),
            ("vacation", "휴가 (미국)"),
            ("abroad", "해외에"),
            ("overseas", "해외로"),
            ("foreign", "외국의"),
            ("international", "국제적인"),
            ("passport", "여권"),
            ("visa", "비자, 사증"),
            ("embassy", "대사관"),
            ("consulate", "영사관"),
            ("currency", "통화"),
            ("exchange rate", "환율"),
            ("money exchange", "환전"),
            ("cash", "현금"),
            ("traveler's check", "여행자 수표"),
            ("local", "현지인, 현지의"),
            ("native", "원주민, 토착의"),
            ("tourist information", "관광 안내소"),
            ("brochure", "브로슈어, 안내 책자"),
            ("pamphlet", "팸플릿, 소책자"),
            ("postcard", "엽서"),
            ("camera", "카메라"),
            ("photograph", "사진"),
            ("journal", "일기, 여행기"),
            ("diary", "일기"),
            ("backpack", "배낭"),
            ("backpacker", "배낭여행객"),
            ("solo travel", "혼자 하는 여행"),
            ("group travel", "단체 여행"),
            ("budget travel", "저예산 여행"),
            ("luxury travel", "고급 여행"),
            ("insurance", "보험"),
            ("travel insurance", "여행자 보험"),
            ("vaccination", "예방 접종"),
            ("jet lag", "시차증"),
            ("adapt", "적응하다"),
            ("culture", "문화"),
            ("custom", "관습"),
            ("tradition", "전통"),
            ("language", "언어"),
            ("barrier", "장벽"),
            ("language barrier", "언어 장벽"),
            ("phrasebook", "상용 회화집"),
            ("translate", "번역하다"),
            ("interpret", "통역하다"),

            // 9. Types of Trips (여행 종류)
            ("adventure travel", "모험 여행"),
            ("backpacking", "배낭여행"),
            ("beach holiday", "해변 휴가"),
            ("business trip", "출장"),
            ("camping", "캠핑"),
            ("city break", "단기 도시 여행"),
            ("cruise", "크루즈 여행"),
            ("cultural travel", "문화 여행"),
            ("eco-tourism", "생태 관광"),
            ("gap year", "갭 이어 (학업/취업 전 여행)"),
            ("honeymoon", "신혼여행"),
            ("pilgrimage", "순례 여행"),
            ("road trip", "자동차 여행"),
            ("safari", "사파리 여행"),
            ("skiing trip", "스키 여행"),
            ("solo trip", "1인 여행"),
            ("staycation", "스테이케이션 (집 근처 휴가)"),
            ("volunteering", "봉사 여행"),
            ("weekend break", "주말 여행"),
            ("working holiday", "워킹 홀리데이"),
            ("excursion", "짧은 여행, 소풍"),
            ("outing", "야유회, 짧은 외출"),
            ("getaway", "짧은 휴가"),
            ("leisure travel", "여가 여행"),
            ("package holiday", "패키지 휴가"),
            ("self-catering", "직접 요리하는 (숙박)"),
            ("sightseeing tour", "관광 투어"),
            ("trekking", "트레킹"),
            ("hiking", "하이킹"),
            ("family vacation", "가족 휴가"),

            // 10. Geography & Nature (지리 및 자연)
            ("beach", "해변"),
            ("coast", "해안"),
            ("shore", "해안, 물가"),
            ("island", "섬"),
            ("peninsula", "반도"),
            ("ocean", "대양"),
            ("sea", "바다"),
            ("lake", "호수"),
            ("river", "강"),
            ("stream", "시냇물"),
            ("waterfall", "폭포"),
            ("mountain", "산"),
            ("hill", "언덕"),
            ("valley", "계곡"),
            ("canyon", "협곡"),
            ("cave", "동굴"),
            ("forest", "숲"),
            ("jungle", "정글"),
            ("rainforest", "열대 우림"),
            ("desert", "사막"),
            ("oasis", "오아시스"),
            ("volcano", "화산"),
            ("glacier", "빙하"),
            ("cliff", "절벽"),
            ("bay", "만"),
            ("lagoon", "석호 (바다와 분리된 호수)"),
            ("reef", "암초, 산호초"),
            ("coral reef", "산호초"),
            ("island hopping", "여러 섬 돌아다니기"),
            ("nature reserve", "자연 보호 구역"),
            ("wildlife", "야생 동물"),
            ("scenic", "경치가 좋은"),
            ("breathtaking", "숨이 멎을 듯한"),
            ("picturesque", "그림 같은"),
            ("remote", "외딴, 먼"),
            ("isolated", "고립된"),
            ("unspoiled", "훼손되지 않은, 자연 그대로의"),
            ("tropical", "열대의"),
            ("temperate", "온대의"),
            ("arid", "건조한"),
            ("humid", "습한"),
            ("climate", "기후"),
            ("weather", "날씨"),
            ("forecast", "예보"),
            ("sunrise", "일출"),
            ("sunset", "일몰"),
            ("horizon", "수평선, 지평선"),
            ("altitude", "고도"),
            ("landscape", "풍경"),
            ("environment", "환경"),

            // 11. Problems & Emergencies (문제 및 응급상황)
            ("lost", "길을 잃은"),
            ("stolen", "도난당한"),
            ("theft", "도난"),
            ("robbery", "강도"),
            ("pickpocket", "소매치기"),
            ("scam", "사기"),
            ("fraud", "사기"),
            ("emergency", "응급 상황"),
            ("accident", "사고"),
            ("injury", "부상"),
            ("injured", "다친"),
            ("sick", "아픈"),
            ("ill", "아픈"),
            ("illness", "질병"),
            ("fever", "열"),
            ("headache", "두통"),
            ("stomachache", "복통"),
            ("food poisoning", "식중독"),
            ("medicine", "약"),
            ("pharmacy", "약국"),
            ("drugstore", "약국"),
            ("hospital", "병원"),
            ("clinic", "병원, 진료소"),
            ("doctor", "의사"),
            ("nurse", "간호사"),
            ("ambulance", "구급차"),
            ("police", "경찰"),
            ("police station", "경찰서"),
            ("report", "신고하다"),
            ("lost and found", "분실물 센터"),
            ("consulate", "영사관"),
            ("embassy", "대사관"),
            ("danger", "위험"),
            ("dangerous", "위험한"),
            ("safe", "안전한"),
            ("safety", "안전"),
            ("precaution", "예방 조치"),
            ("warning", "경고"),
            ("help", "도움"),
            ("assistance", "지원, 도움"),

            // 12. People & Culture (사람 및 문화)
            ("local people", "현지 사람들"),
            ("inhabitant", "주민"),
            ("resident", "거주자"),
            ("foreigner", "외국인"),
            ("stranger", "낯선 사람"),
            ("guide", "가이드"),
            ("host", "주인"),
            ("guest", "손님"),
            ("culture shock", "문화 충격"),
            ("etiquette", "에티켓, 예절"),
            ("manners", "예절"),
            ("greeting", "인사"),
            ("language", "언어"),
            ("dialect", "방언, 사투리"),
            ("religion", "종교"),
            ("belief", "신념"),
            ("value", "가치"),
            ("celebration", "축하 행사"),
            ("holiday (national)", "공휴일"),
            ("traditional", "전통적인"),
            ("modern", "현대적인"),
            ("lifestyle", "생활 방식"),
            ("community", "공동체, 지역 사회"),
            ("society", "사회"),
            ("local custom", "현지 관습"),
            ("souvenir", "기념품"),
            ("handicraft", "수공예품"),
            ("local market", "현지 시장"),
            ("bargain", "흥정하다"),
            ("haggle", "흥정하다"),

            // 13. Descriptive Words (묘사)
            ("amazing", "놀라운"),
            ("awesome", "멋진"),
            ("beautiful", "아름다운"),
            ("boring", "지루한"),
            ("bustling", "붐비는, 활기찬"),
            ("busy", "바쁜"),
            ("calm", "고요한"),
            ("charming", "매력적인"),
            ("cheap", "저렴한"),
            ("affordable", "가격이 알맞은"),
            ("clean", "깨끗한"),
            ("comfortable", "편안한"),
            ("convenient", "편리한"),
            ("crowded", "붐비는"),
            ("dangerous", "위험한"),
            ("dirty", "더러운"),
            ("disappointing", "실망스러운"),
            ("enjoyable", "즐거운"),
            ("exciting", "흥미진진한"),
            ("expensive", "비싼"),
            ("costly", "비용이 많이 드는"),
            ("fantastic", "환상적인"),
            ("fascinating", "매혹적인"),
            ("historic", "역사적인"),
            ("impressive", "인상적인"),
            ("incredible", "믿을 수 없는, 굉장한"),
            ("interesting", "흥미로운"),
            ("lively", "활기찬"),
            ("lovely", "사랑스러운"),
            ("magnificent", "웅장한, 장엄한"),
            ("memorable", "기억에 남을 만한"),
            ("modern", "현대적인"),
            ("noisy", "시끄러운"),
            ("old-fashioned", "구식의"),
            ("peaceful", "평화로운"),
            ("polluted", "오염된"),
            ("quiet", "조용한"),
            ("relaxing", "편안하게 하는"),
            ("safe", "안전한"),
            ("spectacular", "장관을 이루는"),
            ("stunning", "정말 멋진, 기절할 만큼 아름다운"),
            ("terrible", "끔찍한"),
            ("tiring", "피곤하게 하는"),
            ("traditional", "전통적인"),
            ("unforgettable", "잊을 수 없는"),
            ("unusual", "특이한"),
            ("vibrant", "활기찬, 생생한"),
            ("wonderful", "훌륭한"),
            ("worthwhile", "가치 있는"),
            ("unique", "독특한"),
    ]
}
